"""create table

Revision ID: 7fa7ab076259
Revises: 60f5d2b2af0f
Create Date: 2024-05-19 13:38:53.970733

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fa7ab076259'
down_revision: Union[str, None] = '60f5d2b2af0f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('drinks', sa.Column('image', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('drinks', 'image')
    # ### end Alembic commands ###
